// src/data/descriptionData.js
export const descriptionData = [
  {
    id: 1,
    name: "Watch",
    description: "A stylish and durable watch, perfect for everyday wear or formal occasions. Made with precision and care to keep you punctual.",
    specifications: {
      Brand: "Timeless Co.",
      Material: "Stainless Steel",
      WaterResistance: "Up to 50 meters",
      BatteryLife: "2 years",
    },
    warranty: "1-year manufacturer warranty",
    returnPolicy: "30-day easy return policy",
  },
  {
    id: 2,
    name: "Robot Toy",
    description: "An interactive robot toy that sparks creativity and fun. Ideal for kids to explore robotics and play with intelligent features.",
    specifications: {
      Brand: "TechPlay",
      AgeGroup: "6+ years",
      Features: "Interactive voice commands, LED lights, dance moves",
      Battery: "Rechargeable (USB charging cable included)",
    },
    warranty: "6-month manufacturer warranty",
    returnPolicy: "15-day easy return policy",
  },
  {
    id: 3,
    name: "Shampoo",
    description: "A nourishing shampoo for all hair types. Keeps your hair clean, smooth, and shiny while being gentle on your scalp.",
    specifications: {
      Brand: "HairCare Pro",
      Volume: "500ml",
      Ingredients: "Argan oil, Vitamin E, Aloe Vera",
      SuitableFor: "All hair types",
    },
    warranty: "N/A",
    returnPolicy: "Non-returnable",
  },
  {
    id: 4,
    name: "T-Shirt",
    description: "A comfortable and trendy t-shirt, perfect for casual outings or lounging at home. Made with high-quality fabric for a soft feel.",
    specifications: {
      Brand: "StyleWear",
      Material: "100% Cotton",
      Fit: "Regular Fit",
      Sizes: "S, M, L, XL",
    },
    warranty: "N/A",
    returnPolicy: "30-day easy return policy",
  },
  {
    id: 5,
    name: "Cap",
    description: "A stylish cap to complete your look. Lightweight and breathable, it's perfect for sunny days or casual wear.",
    specifications: {
      Brand: "TopHead",
      Material: "Polyester",
      Adjustable: "Yes",
      Sizes: "One size fits all",
    },
    warranty: "3-month manufacturer warranty",
    returnPolicy: "30-day easy return policy",
  },
  {
    id: 6,
    name: "Shoe",
    description: "Durable and fashionable shoes for all occasions. Offers excellent comfort and grip for your busy lifestyle.",
    specifications: {
      Brand: "FootEase",
      Material: "Synthetic Leather",
      Sole: "Rubber",
      Sizes: "7, 8, 9, 10, 11",
    },
    warranty: "1-year manufacturer warranty",
    returnPolicy: "30-day easy return policy",
  },
  {
    id: 7,
    name: "Slipper",
    description: "Comfortable and lightweight slippers for daily use. Perfect for indoor and outdoor settings.",
    specifications: {
      Brand: "ComfyFeet",
      Material: "EVA Foam",
      Waterproof: "Yes",
      Sizes: "6, 7, 8, 9, 10",
    },
    warranty: "6-month manufacturer warranty",
    returnPolicy: "30-day easy return policy",
  },
  {
    id: 8,
    name: "Bag",
    description: "A spacious and durable bag, ideal for travel or daily use. Combines style and practicality effortlessly.",
    specifications: {
      Brand: "CarryMore",
      Material: "Nylon",
      Capacity: "30L",
      Features: "Waterproof, Multiple compartments, Adjustable straps",
    },
    warranty: "1-year manufacturer warranty",
    returnPolicy: "30-day easy return policy",
  },
];
